# SPDX-License-Identifier: GPL-2.0-only

SYNC_FENCE_ROOT := $(srctree)/techpack/mm

LINUXINCLUDE    += -I$(SYNC_FENCE_ROOT)/sync_fence/include/
include $(SYNC_FENCE_ROOT)/config/kalamammdrivers.conf
LINUXINCLUDE += -include $(SYNC_FENCE_ROOT)/config/kalamammdriversconf.h

ifdef CONFIG_QCOM_SPEC_SYNC
obj-m += sync_fence.o

sync_fence-y := src/qcom_sync_file.o

CDEFINES += -DBUILD_TIMESTAMP=\"$(shell date -u +'%Y-%m-%dT%H:%M:%SZ')\"
endif
